-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: May 04, 2018 at 01:59 PM
-- Server version: 5.7.15-log
-- PHP Version: 7.0.11

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `chatbot`
--

-- --------------------------------------------------------

--
-- Table structure for table `list_ques`
--

CREATE TABLE `list_ques` (
  `id` int(11) NOT NULL,
  `question` text CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL,
  `answer` text CHARACTER SET utf8 COLLATE utf8_vietnamese_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `list_ques`
--

INSERT INTO `list_ques` (`id`, `question`, `answer`) VALUES
(170, ' Em đang muốn tham gia dự thi ngành Công Nghệ Thông Tin trường mình. Em muốn nhận được tư vấn như học phí, thời gian, và điều kiện tuyển sinh của trường ạ', 'Chào bạn,Ngành CNTT tuyển sinh theo nhóm ngành CNTT có mã nhóm ngành là CN1, chỉ tiêu nhóm ngành CNTT là 420, xét tuyển theo 3 tổ hợp A00, A01 và D07, điểm xét tuyển là tổng hợp điểm của 3 môn trên thang điểm 30. Học phí chương trình này năm học 2018-2019 là 9.6 triệu/năm.Thời gian đào tạo 4 năm.'),
(171, 'Dạ cho em hỏi. Em trai em học Chuyên Thái Bình và đạt giải khuyến khích thi Toán Quốc gia. Vậy có được cộng điểm khi ứng tuyển vào trường không ạ? Trong hồ sơ nộp cần giấy tờ gì để nhận diện là học sinh đạt giải không ạ?', 'Chào bạn,\nTrường ĐH Công nghệ chỉ xét tuyển theo kết quả thi THTP quốc gia và không xét các tiêu chí khác.'),
(172, 'Ngành công nghệ thông tin của trường năm ngoái lấy bn ạ??', 'Chào em, Ngành CNTT năm ngoái lấy 26 em nhé.\nEm có thể tham khảo điểm chuẩn các năm tại đây:https://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/.'),
(173, 'Cho em hỏi mã ngành của trường có phải là chữ k ạ', 'Chào em,Trường ĐHCN mã trường là QHI em nhé.\nEm có thể tham khảo thông tin tại đây: https://uet.vnu.edu.vn/thong-tin-de-tuyen-sinh-cua-truong-dai-hoc-cong-nghe-nam-2018/'),
(174, ' Ngành công nghệ kỹ thuật điện tử,  truyền thông clc năm nay xét thế nào', 'Chào em, Ngành CNKT ĐT-VT CLC được xét tuyển theo kết quả thi THPT quốc gia với 3 tổ hợp môn là A00, A01,D07, trong đó toán anh hoặc toán lý được nhân hệ số 2, hoặc theo chứng chỉ A-level.\nBạn cần tư vấn cứ hỏi nhà trường sẽ trả lời nhé.'),
(175, 'em là học sinh cấp 3 trường chuyên Khoa học tự nhiên thì có điều kiện gì để xét tuyển thẳng vào đại học Công nghệ không ạ (em được 3 năm học sinh giỏi),em học lớp chuyên Tin', 'Chào em, Học sinh THPT chuyên thuộc ĐHQGHN được xét tuyển thẳng và xét tuyển vào bậc đại học tại ĐHQGHN phải đỗ tốt nghiệp THPT, có hạnh kiểm 3 năm học THPT đạt loại Tốt và đáp ứng một trong các tiêu chí sau:\n+ Là thành viên chính thức đội tuyển dự kỳ thi Olympic hoặc các cuộc thi sáng tạo,triển lãm khoa học kỹ thuật khu vực, quốc tế;\n+ Đạt giải chính thức trong kỳ thi chọn học sinh giỏi bậc THPT cấp ĐHQGHN;\n+ Đạt giải chính thức trong kỳ thi Olympic chuyên Khoa học tự nhiên bậc THPT được tổ chức hàng năm;\n+ Là thành viên chính thức của đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia hoặc các cuộc thi sáng tạo khoa học kỹ thuật quốc gia;\n+ Đạt danh hiệu học sinh giỏi từng năm học trong cả 3 năm THPT và có tổng điểm 4 bài thi/môn thi tốt nghiệp THPT đạt tối thiểu 28,0 điểm trong đó không có điểm bài thi/môn thi nào dưới 5,0 điểm;\nNếu em là hs giỏi 3 năm thì phải có tổng điểm 4 bài thi từ 28 điểm trở lên và ko môn nào dưới 5 em nhé.\nChúc em thi tốt và hẹn gặp em tại trường ĐH Công nghệ.\n\n'),
(176, 'Em đang muốn tham gia dự thi ngành Công Nghệ Thông Tin trường mình. Em muốn nhận được tư vấn như học phí, thời gian, và điều kiện tuyển sinh của trường ạ', 'Chào em, Ngành CNTT tuyển sinh theo nhóm ngành CNTT có mã nhóm ngành là CN1, chỉ tiêu nhóm ngành CNTT là 420, xét tuyển theo 3 tổ hợp A00, A01 và D07, điểm xét tuyển là tổng hợp điểm của 3 môn trên thang điểm 30.\nHọc phí chương trình này năm học 2018-2019 là 9.6 triệu/năm.\nThời gian đào tạo 4 năm.'),
(177, 'Chào bạn, mình đang quan tâm đến Trường đại học Công nghệ - Đại học quốc gia Hanoi', 'Chào bạn, bạn muốn hỏi về điều gì? Nhà trường gửi bạn một số thông tin bạn có thể tham khảo:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/news/QHI'),
(178, 'Thầy/ cô cho em mẫu phiếu đăng ký xét tuyển thẳng vào trường được không ạ. Em cảm ơn', 'Chào em, em xem hướng dẫn: https://uet.vnu.edu.vn/huong-dan-cong-tac-tuyen-sinh-dai-hoc/'),
(179, ' Nhà trường cũng cho em hỏi là khi mà em được tuyển thẳng rồi ấy ạ, thì em muốn thi vào các lớp chất lượng cao thì phải thi bằng môn gì ạ ? ( ví dụ như toán với lý chẳng hạn )', 'Chào em, Nhà trường có chương trình CLC ngành CNTT để vào lớp này em sẽ phải trải qua 1 kỳ thi nữa là Lập trình và tiếng Anh.\nChương trình CLC theo thông tư 23 gồm 2 ngành KHMT và CNKT ĐT-VT thì em sẽ được tuyển thẳng mà không phải thi thêm nữa.'),
(180, 'Mã tuyển sinh của nhóm ngành công nghệ thông tin của trường mình năm 2018 là gì vậy ạ?', 'Chào em, Mã TS nhóm ngành Công nghệ thông tin là CN1.\nEm tham khảo tại đây nhé:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI'),
(181, 'Cho em hỏi mã ngành của khoa học máy tính (CLC)  là gì với ạ ??', 'Chào em, Mã ngành ngành KHMT (CLC theo TT23) là CN8.\nEm tham khảo tại đây: http://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI'),
(182, 'cho e hỏi mã nghành công nghệ thông tin là gì vậy ạ', 'Chào em, Ngành CNTT tuyển sinh theo nhóm ngành. Mã nhóm ngành là CN1, tên nhóm ngành là Công nghệ thông tin.'),
(183, ' Nhà trường cho em hỏi là ở trong đề án tuyển sinh 2018 của nhà trường ( trang 6 ) thì có ghi rõ là chỉ tiêu tuyển thẳng là 66 người nhưng mà tại sao hôm qua nhà trường lại nói là tuyển không thẳng không giới hạn ạ? Em mong nhà trường giải thích rõ cho em điều này để em khỏi nhầm lẫn ạ, em xin cám ơn.', 'Chào em, em không cần lo lắng quá, vì mỗi trường khi tuyển sinh đều có phát sinh. Riêng tuyển thẳng là các trường hợp nhà trường ưu tiên xét tuyển, nên sẽ tạo điều kiện. Em cứ yên tâm nhé.'),
(184, 'Em cảm ơn ạ, nhà trường cho em hỏi là năm nay là trường Đại Học Công Nghệ , ĐHQGHN tuyển thẳng không giới hạn đúng không ạ , tức là em bây giờ chỉ cần nạp đầy đủ hồ sơ tuyển thẳng thì sẽ được tuyển thẳng luôn đúng không ạ?', 'Tuyển thẳng là các trường hợp nhà trường ưu tiên xét tuyển, nên sẽ tạo điều kiện. Em cứ yên tâm nộp hồ sơ nhé.'),
(185, 'Thầy/ cô cho em hỏi thêm, trong phiếu đăng kí xét tuyển thẳng của bộ GDĐT như hình đính kèm: ở thông tin số 7 và số 8 chỉ điền được một năm, một loại giải, mà em lại đạt hai năm hai giải, nên bây giờ em viết vào đó giải nhì về lĩnh vực "kĩ thuật cơ khí", hay giải ba về lĩnh vực "robot và thông minh" thì mới gần ngành "kĩ thuật robot" ạ! Em sợ nếu viết vào đó giải nhì lĩnh vực "kĩ thuật cơ khí" thì lại không gần với ngành "kĩ thuật robot", còn viết vào giải ba lĩnh vực "robot và máy thông minh" thì giải thấp hơn, cơ hội được tuyển cũng sẽ thấp hơn. Mong thầy/ cô tư vấn, Em cảm ơn !', 'Chào em, Nhà trường giải thích cho em như sau: các giải em đạt được này được bảo lưu đến khi em tốt nghiệp THPT nên giải năm lớp 10 hay 11, 12 đều có giá trị như nhau. Thứ 2, cả 2 lĩnh vực của em đều phù hợp để tuyển thẳng vào ngành Kỹ thuật robot. Thứ 3, các trường hợp tuyển thẳng nhà trường ưu tiên các em trước nên em không sợ có cạnh tranh. Vì vậy việc ghi hồ sơ em ghi giải nào cũng được em nhé.\n\n'),
(186, 'Thầy/ cô cho em hỏi, năm học 2016-2017 em có đạt giải nhì Khoa học kĩ thuật cấp quốc gia lĩnh vực kĩ thuật cơ khí, năm học 2017-2018 em đạt giải ba cấp quốc lĩnh vực Robot và máy thông minh. Vậy em có được tuyển thẳng vào ngành kĩ thuật robot của trường không ạ, và nếu được tuyển thẳng thì hồ sơ em cần những gì và trong hồ sơ ghi cả hai giải hay chỉ ghi giải cao nhất ạ. Em mong nhận được câu trả lời sớm nhất từ Thầy/ Cô.\nEm cảm ơn!', 'Chào em, em được tuyển thẳng vào ngành kỹ thuật robot em nhé. Thí sinh đoạt giải nhất, nhì, ba trong kỳ thi chọn học sinh giỏi quốc gia; thí sinh đoạt giải nhất, nhì, ba trong Cuộc thi khoa học, kỹ thuật cấp quốc gia, đã tốt nghiệp THPT, được tuyển thẳng vào đại học theo ngành phù hợp với môn thi hoặc nội dung đề tài dự thi mà thí sinh đã đoạt giải.\nHồ sơ em cần theo yêu cầu của bộ:\nhttps://uet.vnu.edu.vn/huong-dan-cong-tac-tuyen-sinh-dai-hoc/\nphần tuyển thẳng em nhé.\nEm lưu ý hồ sơ chuyển về sở trước ngày 20/5/2018.\nChào đón em tại trường Đại học Công nghệ.\n\n'),
(187, 'Xin chào nhà trường , e là Nguyễn Trọng Thủy hiện đang là học sinh lớp 12 ,e xin hỏi nhà trường về vấn đề : Em có tham gia cuộc thi IEYI (sáng tạo TTN ở VN do quỹ VIFOTECH tổ chức) ở Malaysia năm 2013: được Huy chương vàng , năm 2014: huy chương bạc , Và năm 2015 tổ chức ở Đài Loan được Huy chươngđồng . Bằng khen của macao , hong kong. (bằng khen của Bộ GD-ĐT  , TW đoàn TNCS HCM ..). Nên em muốn hỏi là em có thể được tuyển thẳng hay có thể được ưu tiên không ạ để học ở trường không ạ , em xin cảm ơn (E sinh năm 2000)(Không nằm trong quy chế tuyển thẳng bộ GD-ĐT)\n\n', 'Chào em, em có là học sinh của trường THPT chuyên trong ĐHQG không? Nếu không thi không được em ạ. Em có thể tham khảo mục 2.8 đề án tuyển sinh của trường.'),
(188, 'Ở tờ đăng kí dự thi 1 và 2. E vội quá nên nhờ bạn e ghi hộ 1 tờ và e ghi 1 tờ nên chữ nhìn khác nhau. Nhưng vẫn cùng màu mực ạ. Thi e hỏi như thế có bị làm sao không ạ?\n\n', 'Không sao em ạ. Quan trọng là thông tin giống nhau là được.'),
(189, ' Sao em tìm mã trường Đại học công nghệ hà nội trên thituyensinh.vn mà không có ạ', 'Chào em, chắc hệ thống đang lỗi.\nEm tham khảo đề án tuyển sinh của trường tại đây em  nhé:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewpage/24'),
(190, ' cho em hỏi là ngành công nghệ thông tin của trường mình có lấy nguyện vọng 2 không ạ', 'Chào em, nguyên tắc xét điểm là xét từ cao xuống thấp đến khi đủ điểm vào một trong các nguyện vọng của em. Nếu điểm của em đủ đỗ vào 2 hoặc 3 nguyện vọng em đã đăng ký thì nguyện vọng đầu\ntiên được xét trước và em sẽ trúng tuyển vào ngành đó, các nguyện vọng 2 hoặc 3 kia không còn được xét đến nữa mặc dù em đủ điểm đỗ. Do đó ưu tiên của em sẽ là ngành nào yêu thích được xếp lên đầu.'),
(191, ' Em muốn nhận thông tin về vấn đề tuyển sinh đại học của trường.', 'Đề án tuyên sinh của trường: http://tuyensinh.vnu.edu.vn/index.php/Home/viewpage/24'),
(192, 'Có dao tao cơ điện tử hk', 'Chào em, Nhà trường có đào tạo ngành Công nghệ kỹ thuật cơ điện tử. Em có thể tham khảo các ngành của\ntrường tại đây:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\n\n'),
(193, 'ạ e chào ac ạ cho em hỏi em ở khu vực 2 ạ em muốn tìm điểm chuẩn của ngành mạng máy tính và truyền thông dữ liệu năm 2017 láy bao nhiêu điểm ạ\n\n', 'Chào em, năm ngoái mạng máy tính và tuyền thông dữ liệu lấy 26 điểm em nhé. Chị gửi em thông tin điểm chuẩn các năm: https://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\n\n'),
(194, 'dạ em cảm ơn ạ chị ơi cho em hỏi ngành này con gái có phải là sau khi ra trường sẽ rất khó xin việc đúng k ạ', 'Chào em, không ngành nào là khó xin việc cả em ạ. Lĩnh vực công nghệ kỹ thuật luôn khát nhân lực, em có thể tham khảo cơ hội việc làm của sinh viên đại học Công nghệ 2 khóa ra trường gần đây nhất:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/160\nBài viết sau phân tích về tỉ lệ có việc làm của sv nữ:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/77\nNên em không cần phải lo lắng em nhé.\nYên tâm học tốt thôi.'),
(195, '  Em muốn hỏi là ngành công nghệ thông tin định hướng thị trường Nhật Bản là học tiếng nhật rồi thi vào hay là đến lúc đấy mới bắt đầu học tiếng ạ\n\n', 'Chào em, Ngành CNTT định hướng thị trường Nhật Bản sẽ được học tiếng Nhật khi các em bắt đầu vào học. Ngành này cũng xét tuyển các tổ hợp A00, A01, D07 như các ngành khác.\n\n'),
(196, 'Nhưng thứ 7 tuần trước em đăng ký nguyện vọng rồi, mà hôm nay bên tuyển sinh mới trả lời, em muốn hỏi là bây giờ em muốn đăng ký ngành này có được không ạ\n\n', 'Chào em, Nếu em muốn thì vào ngành này em có thể mang phiếu số 2 đến điểm thu hồ sơ của em để xin đổi lại, còn nếu không được em còn 1 lần điều chỉnh nguyện vọng sau khi đã biết điểm thi THPT quốc gia em nhé.\n\n'),
(197, 'Em hiện đang là học sinh lớp 12. Em có dự định thi vào trường, thầy (cô) có thể cho em hỏi một vài điều được không ạ?', 'Chào em, em quan tâm đến ngành nào? Em muốn hỏi điều gì? Nhà trường gửi cho em một số thông tin tuyển sinh của trường để em tham khảo nhé. Các ngành:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nGiới thiệu về ngành:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nEm cần thông tin chi tiết hơn có thể gọi: 02437547810\n\n'),
(198, 'Em muốn đăng ký ngành công nghệ thông tin và em muốn hỏi một vài thông tin về ngành này.\n\n', 'Chào em, như trong giới thiệu về ngành chị đã gửi ở dưới, chị cũng trao đổi thêm rằng ngành CNTT hiện nay vẫn đang là 1 ngành khát nhân lực. Nhu cầu tuyển dụng đang rất lớn, quan trọng là sinh viên ra có làm được việc không. Học ở trường ĐHCN chị muốn em xác định rằng em học sẽ vất vả, không thể vừa học vừa chơi. Trường ĐHCN mong muốn sinh viên của mình khi ra trường phải làm được việc và khẳng định thương hiệu của ĐHCN nên yêu cầu sinh viên phải có kiến thức thật, học thật và thi thật em nhé. Chị gửi em tham khảo khung chương trình ngành CNTT:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-thong-tin/\n\n'),
(199, '\nNếu em chưa biết gì về lập trình thì có học được ngành này không ạ? Em đang học khối A1 nhưng tiếng anh của em cũng không được tốt lắm, vậy có học được công nghệ thông tin không ạ?\n\n', 'Chào em, khi em trúng tuyển thì nhà trường sẽ đào tạo căn bản từ đầu cho các em chưa biết gì. Cũng tương tự, tiếng Anh là kỹ năng quan trọng, là công cụ để em đọc tài liệu, nghiên cứu, cũng như đáp ứng được yêu cầu của xã hội hội nhập ngày nay. Nên trong quá trình học em sẽ được trau dồi và tích lũy dần. Chúc em học và thi tốt.\n\n'),
(200, ' Cho em hỏi học phí một năm học vào khoảng bao nhiêu ạ?', 'Chào em, học phí hệ chuẩn năm 2018-2019 là 9.6 triệu/năm, mỗi năm sẽ tăng lên theo quy định của nhà nước (mục 2.10)\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=1aeefrqq8a_5&_afrLoop=3200299472642457\nHP chương trình CLC là 35 triệu/năm ổn định trong 4 năm.\n\n'),
(201, 'Em thấy mọi năm trường có tổ chức bài thi đánh giá năng lực, cho em hỏi là năm nay nhà trường có tổ chức không ạ?', 'Chào em, năm nay ĐHQGHN không tổ chức thi ĐGNL. Từ năm 2017 đã xét tuyển theo kết quả kỳ thi THPT quốc gia em nhé.'),
(202, 'Chào admin ạ, năm nay em có ý định thi vào các lớp CLC của trường. Cụ thể là em muốn đăng ký chương trình kỹ thuật máy tính CLC thì cho em hỏi là lớp CLC này thì khác gì so với lớp bình thường và lớp CLC là lấy điểm thi THPTQG của em hay là đến lúc em đỗ vào trường rồi thì mới thi 1 đợt của trường nữa để vào lớp CLC à ? Em cảm ơn ạ!\n\n', 'Nhà trường hiện nay có 2 chương trình CLC.\n1. Chương trình chất lượng cao ngành công nghệ thông tin. Đây là chương trình được tính học phí như của hệ chuẩn. Việc xét vào chương trình này sau khi các em trúng tuyển vào ngành CNTT sẽ phải thi thêm 1 bài thi chuyên môn nữa, chỉ tiêu chương trình này khoảng 25 sinh viên.\n2. Chương trình chất lượng cao theo thông tư 23 có 2 ngành là: Khoa học máy tính và Công nghệ kỹ thuật điện tử-viễn thông. Chương trình chất lượng cao đào tạo theo đơn đặt hàng từ các doanh nghiệp, tổ chức hàng đầu của Nhật Bản, Việt Nam và quốc tế. Tối thiểu 50% môn học chuyên môn được giảng dạy bằng Tiếng Anh. Sử dụng phương pháp giảng dạy, kiểm ra đánh giá theo hướng phát huy năng lực cá nhân, chú trọng phát triển năng lực phân tích, thực hành, sáng tạo, tự cập nhật kiến thức;năng lực nghiên cứu, ứng dụng khoa học và công nghệ. Tất cả các ngành của trường ĐHCN đểu xét tuyển theo kết quả kỳ thi THPT quốc gia. Riêng chương trình CLC theo thông thư 23 thì chấp nhận chứng chỉ A-level.\n \n'),
(203, 'Và cho em hỏi thêm một câu hỏi nữa là ngành Khoa học máy tính CLC theo TT23 năm ngoái xét đến nguyện vọng mấy là dừng ạ ?\n\n', 'Chào em, Ngành KHMT CLC theo TT23 năm ngoái lấy 24 điểm. Nhà trường xét theo điểm không theo nguyện vọng, tức là có thể là nguyện vọng thứ n cũng được miễn là em 24 điểm vào chưa đỗ vào ngành nào khác.\nThân mến.\n\n'),
(204, 'cho e hỏi, e muốn thi vào trường thì ở hồ sơ của e, phần nguyện vọng ý, phần mã ngành, nhóm ngành e phải ghi như thế nào ạ', 'Chào bạn, Nhà trường gửi bạn hướng dẫn viết hồ sơ:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-\ndang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nBạn cần thông tin chi tiết hơn có thể gọi điện theo số: 02437547810.\n\n'),
(205, 'e muốn xét tuyển vào ngành cong nghệ thông tin định hướng thị trường nhật bản thì mục tên ngành/ nhóm ngành ghi như thế nào ạ', 'Chào em, như hướng dẫn chị gửi ở dưới. Ngành CNTT định hướng thị trường Nhật Bản nằm trong nhóm ngành CNTT nên em khi mục tên ngành nhóm ngành là CNTT em nhé. Sau khi trúng tuyển vào nhóm nhà trường mới xét các em vào ngành theo nguyện vọng chỉ tiêu và điểm của các em.\n\n'),
(206, 'Xin chào, Năm nay em trai tôi có dự định đăng ký xét tuyển vào quý trường, vui lòng cho tôi hỏi cách tính điểm để xét tuyển cho ngành Công nghệ thông tin(CN1) nhé. Xin cảm ơn!', 'Chào em, Nhà trường xét tuyển theo kết quả kỳ thi THPT quốc gia. Ngành CNTT trong nhóm ngành Công nghệ\nthông tin có mã nhóm ngành là CN1. Tổng chỉ tiêu nhóm ngành là 420 chỉ tiêu. Nhà trường tuyển sinh theo nhóm ngành, việc phân ngành được thực hiện sau khi thí sinh trúng tuyển vào nhóm ngành dựa trên nguyện vọng, chỉ tiêu và điểm của sinh viên. Cách tính điểm được tính bằng tổng của 3 môn trong tổ hợp xét tuyển tính trên thang điểm 30. Các tổ hợp xét tuyển gồm: A00, A01 và D07.\nChi tiết bạn xem tại đây: http://tuyensinh.vnu.edu.vn/index.php/Home/viewpage/24\n\n'),
(207, 'dạ e chào ac ạ cho em hỏi em ở khu vực 2 ạ em muốn tìm điểm chuẩn của ngành mạng máy tính và truyền thông dữ liệu năm 2017 lấy bao nhiêu điểm ạ\n\n', 'Chào em, Năm ngoái mạng máy tính và tuyền thông dữ liệu lấy 26 điểm em nhé. Chị gửi em thông tin điểm chuẩn các năm:\nhttps://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\n\n'),
(208, 'em chào thầy cô, năm nay em có nguyện vọng đăng ký vào đh công nghệ đại học quốc gia hà nội, thầy cô cho e hỏi, em muốn đăng ký vào ngành : công nghệ thông tin và hệ thống thông tin của CN1, thì em đăng ký làm 2 nguyện vọng hay đăng ký làm 1 nguyện vọng, rồi phân ngành sau ạ, em cám ơn thầy cô\n\n', 'Chào em, Chị gửi em hướng dẫn cách đăng ký:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/213\nNhà trường xét tuyển theo nhóm ngành, 2 ngành mà em yêu thích đều thuộc nhóm ngành Công nghệ thông tin có mã nhóm ngành là CN1. Nên em chỉ cần đăng ký 1 lần cho mã nhóm CN1. Sau khi trúng tuyển vào nhóm ngành, việc phân ngành được thực hiện dựa trên nguyện vọng, điểm và chỉ tiêu em nhé. Hẹn gặp em tại trường Đại học Công nghệ nhé.\n\n'),
(209, 'Thầy/ cô cho em hỏi, năm học 2016-2017 em có đạt giải nhì Khoa học kĩ thuật cấp quốc gia lĩnh vực kĩ thuật cơ khí, năm học 2017-2018 em đạt giải ba lĩnh vực Robot và máy thông minh. Vậy em có thể được tuyển thẳng vào ngành kĩ thuật cơ điện tử trường đại học công nghệ - đại học QGHN không ạ, và nếu được tuyển thẳng thì có cần điều kiện gì về điểm thi THPTQG hay chỉ cần tốt nghiệp là đủ ạ? Em mong nhận được câu trả lời sớm nhất từ Thầy/ Cô.Em cảm ơn!\n\n', 'Chào em, Em hoàn toàn có thể được tuyển thẳng vào ngành kỹ thuật cơ điện tử. Điều kiện được tuyển thẳng là\nem phải tốt nghiệp THPT. Em lưu ý hồ sơ tuyển thẳng theo hướng dẫn của Bộ và phải nộp về sở GD&ĐT trước ngày 20/05/2018. Chào mừng em trở thành sinh viên trường Đại học Công nghệ, ĐHQGHN.\nThân mến.\n\n'),
(210, 'em muốn hỏi là tuyển sinh ngành kỹ thuật robot thì điểm chuẩn bằng với kỹ thuật máy tính hay sao vậy???', 'Chào em, Nhà trường xét tuyển theo nhóm ngành, nên điểm trúng tuyển của nhóm ngành là điểm chuẩn của các ngành trong đó. Em lưu ý 2 ngành này thuộc nhóm ngành Máy tính và Robot nên khi đăng ký em ghi mã nhóm ngành là CN2 và tên nhóm ngành là Máy tính và Robot.'),
(211, 'Em muốn hỏi ngành tự động hóa là CN6 : Kỹ thuật cơ điện tử ạ ? Với lại nếu e đăng kí nguyện vọng là CN6 thì chỉ có mỗi ngành đấy thôi nhỉ ? Kiểu e đăng kí CN1 thì có tận 4 ngành trong đấy , CN6 là chỉ 1 ngành hay bao gồm cả nhóm ngành kĩ thuật ạ ?  Thầy cô phân biệt cho e công nghệ thông tin vs kỹ thuật máy tính với , cả tự động hóa vs CNTT thì nên học cái nào nhỉ ?\n\n', 'Chào em, Ngành Công nghệ Kỹ thuật cơ điện tử có mã là CN6 chỉ có 1 ngành này thôi, nên khi em trúng tuyển vào CN6 thì trúng tuyển vào ngành này luôn. Kỹ thuật máy tính em có thể tham khảo tại đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/151\nCông nghệ kỹ thuật cơ điện tử em có thể tham khảo tại đây:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-co-dien-tu/\nNói chung cả 2 ngành em đề cập ở đây đều là các ngành có tính liên ngành kết hợp Điện tử viễn thông, Cơ, và CNTT. Đây chính là xu thế việc làm của nền cách mạng công nghiệp 4.0 hiện nay. Quan trọng là em cảm thấy yêu thích cái nào hơn thôi. Chị nghĩ ngành nào có hấp dẫn riêng. Chúc em ôn và thi thật tốt.\n\n'),
(212, 'Chị ơi , e muốn hỏi thêm cái nè\n+) đăng kí nguyện vọng trc r cơ lúc có điểm thì thay đổi nguyện vọng thì có bị chuyển qua xét tuyển đợt 2 ko ạ ? E thấy có bạn bảo ko thay đổi nguyện vọng đc ưu tiên hơn .\n+) nếu trượt nv1 thì phải đến đợt sau mới được xét nv2 hay là xét tất cả nv như nhau còn nv1 là tiêu chí phụ ạ ?\n+) nếu thi cả A,A1 thì cứ mỗi trg mất 2 nv ( do 2 tổ hợp ạ ) ? Thế nếu bạn ý định thi 5 nhóm ngành mất 10 nv thì có nên ko ạ ?\n+) chỗ ghi hộ khẩu thường trú thì ghi hẳn số nhà hay mỗi quận , tp ,..\n\n', '1. Sau khi biết điểm các em có 1 lần được thay đổi nguyện vọng. Điều này không ảnh hưởng gì đến việc thay đổi hay không thay đổi nguyện vọng ở đây. Bởi sau khi thay đổi này mới xét tuyển.\n2. Điểm sẽ được xét từ trên xuống dưới theo thứ tự nguyện vọng của em cho đến khi em đủ điểm đỗ vào một ngành nào đó trong danh sách nguyện vọng của em. Nếu em đủ điểm đỗ vào nhiều hơn 2 ngành hoặc 2 trường thì ngành nào xếp trước sẽ được xét trước và em ko còn cơ hội học ở ngành xếp nguyện vọng sau.\n3. Điều này không ảnh hưởng vì hệ thống xét theo điểm không theo nguyện vọng. Tức là hệ thống sẽ cứ xét từ trên xuống đến khi em đủ điểm đỗ, nên số lượng nguyện vọng là không giới hạn.\nTuy nhiên điều này là không cần thiết vì sau khi biết điểm em có quyền thay đổi nguyện vọng mà lúc này em đã biết tổ hợp nào mình cao điểm nhất. Nói chung địa chỉ em càng ghi chi tiết càng dễ cho việc liên hệ.\nThân mến.\n\n'),
(213, 'Em muốn học ngành kĩ thuật ô tô thì nên chọn (Công nghệ kỹ thuật cơ điện tử) hay là Cơ kĩ thuật của trương ạ.Em cảm ơn!\n\n', 'Chào em, Cả 2 ngành em nói đều cung cấp các kiến thức liên quan, nhưng gần hơn thì em nên thi ngành Công\nnghệ kỹ thuật cơ điện tử với mã nhóm ngành là CN6 em nhé.\n\n'),
(214, 'nếu em k đổ kì thi sau xét ĐH xong do trường tổ chức thì có được học tại trường ko ạ\n\n', 'Chào em, Nhà trường xét tuyển theo kết quả kỳ thi THPT quốc gia. Khi em đã đỗ vào trường thì em là sinh\nviên của trường. Chị chưa hiểu lắm kỳ thi sau xét ĐH nào? Sau khi em trúng tuyển vào trường thì chỉ\ncó kỳ thi sát hạch trình độ tiếng Anh để xếp lớp và 1 kỳ thi dành cho các em có nguyện vọng được học chương trình CLC ngành CNTT thôi em ạ. Chúc em thi đỗ ĐH Công nghệ nhé.\n\n'),
(215, 'Cho em hỏi là năm lớp 11 em đạt giải ba học sinh giỏi quốc gia môn toán và năm 12 đạt giải khuyến khích quốc gia môn toán thì vào năm 2018 này em có được tuyển thẳng vào trường không ạ ? Em cảm ơn.', 'Chào em, Kết quả thi học sinh giỏi quốc gia được bảo lưu đến khi em tốt nghiệp THPT nên kết quả thi năm lớp\n11 của em sẽ được sử dụng tuyển thẳng năm nay được em nhé. Hồ sơ làm theo hướng dẫn của bộ và nộp về sở GDĐT trước ngày 20/05/2018. Em thích vào ngành nào? Nhà trường luôn chào đón các em diện tuyển thẳng đến với ĐH Công nghệ. Nếu em cần tư vấn kỹ hơn cứ trao đổi em nhé.\n\n'),
(216, 'Em muốn tìm hiểu thật kĩ về ngành CNTT của trường : Các chuyên ngành của CNTT, chương trinh đào tạo có kỹ sư ko ạ ? Và phương án tuyển sinh năm 2018 của trường có nhiều đổi mới ko ạ? Em cảm ơn !!!', 'Chào em, Chị gửi em thông tin cũng như chương trình về ngành CNTT:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-thong-tin/\nNhóm ngành CNTT có ngành Mạng máy tính và truyền thông dữ liệu đào tạo kỹ sư. Tuyển sinh năm 2018 tương tự như năm 2017 tức là vẫn xét tuyển theo kết quả thi THPT quốc gia hoặc xét chứng chỉ A level đối với chương trình chất lượng cao TT 23. Chị gửi hướng dẫn đăng ký thi vào ĐH Công nghệ:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\n\n'),
(217, 'Công nghệ thông tin', 'Chào em, Nhà trường gửi bạn thông tin về ngành CNTT:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-thong-tin/\nVà các thông tin tuyển sinh của trường Đại học Công nghệ:\nhttps://uet.vnu.edu.vn/thong-tin-de-tuyen-sinh-cua-truong-dai-hoc-cong-nghe-nam-2018/\nThân mến.\n\n'),
(218, ' phương thức xét tuyển', 'Chào em, Phương thức xét tuyển là xét tuyển theo kết quả thi THPT quốc gia với các tổ hợp môn\ntương ứng.\nChương trình chất lượng cao còn xét chứng chỉ A-level.\nBạn có thể tham khảo tại đây:\nhttps://uet.vnu.edu.vn/thong-tin-de-tuyen-sinh-cua-truong-dai-hoc-cong-nghe-nam-2018/.'),
(219, 'Cho mình hỏi hiện tại đã có xét tuyển đại học chưa ạ', 'Chào em, Hiện tại đang là thời gian đăng ký bạn nhé. Cụ thể bạn có thể xem các hướng dẫn của Bộ.'),
(220, 'Trường có tuyển ngành Thiết kế đồ họa không ạ, và có khối V02 không ạ?', 'Chào em, Trường không có ngành này bạn nhé. Bạn có thể tham khảo các ngành của trường tại đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI'),
(221, 'Chào anh chị, em muốn hỏi mã ngành xét tuyển đại học của ngành CNTT và Khoa học máy tính(CLC) ạ. Khi e tra mã ngành 2 ngành đó trên internet thì nhận được các kết quả khác nhau. Mong sẽ được anh chị phản hồi sớm\n\n', 'Chào em, Em có thể tham khảo hướng dẫn đăng ký ở\nđây:https://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nMã nhóm ngành em nhé: CN1 và CN8.'),
(222, 'cho em xin mã các ngành và tên đc ko ạ', 'Chào em, Chị gửi hướng dẫn đăng ký để em tham khảo:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nChúc em ôn và thi tốt.'),
(223, 'em thấy năm này không còn ngành khoa học máy tính đào tạo chương trình bình thường như năm ngoái nữa là sao vậy ạ??  còn ngành khoa học máy tính CLC thì theo em tìm hiểu là dạy chương trình bằng tiếng anh mà tiếng anh của em kém lắm, không biết học được không??\n\n', 'Chào em, Hiện nay Trường chỉ tuyển sinh ngành KHMT CLC. CHương trình này sẽ có tối thiểu 50% môn học chuyên môn giảng dạy bằng tiếng Anh. Nhưng em không phải quá lo lắng, khi em trúng tuyển vào ngành này thì sẽ được kiểm tra trình độ đầu vào để phân lớp. Ngay trong năm đầu tiên các em sẽ được đầu tư tiếng Anh để có đủ khả năng học bằng ngoại ngữ này. Chị nghĩ rằng là các em có thể vượt qua kỳ thi đại học thì hoàn toàn có thể vượt qua 1 môn ngoại ngữ. Nếu cảm thấy chưa yên tâm nữa thì em có thể lựa chọn các chương trình chuẩn. Trong ngành CNTT cũng có định hướng KHMT nếu em cảm thấy vẫn yêu thích. Chúc em có những lựa chọn phù hợp, ôn và thi tốt.\n\n'),
(224, 'con em năm nay thi đại học nhưng kg hiểu về đăng ký nguyện vọng xin giải thích cho em với', 'Chào chị, Đối với xét tuyển đại học theo kết quả thi THPTQG thì không giới hạn nguyện vọng. Tuy nhiên các em cần lưu ý việc đăng ký nguyện vọng cần cân nhắc ngành nào yêu thích hơn, trường nào yêu thích hơn phải xếp thứ tự ưu tiên bên trên, bởi nếu điểm của em có thể đỗ vào nhiều ngành, hoặc nhiều trường thì ngành nào ở trên sẽ được xét trước và các ngành sau không còn được xét nữa. Việc xét nguyện vọng của các em phần mềm sẽ thực hiện theo nguyên tắc, xét từ trên xuống đến khi điểm của em đủ để trúng tuyển vào một trong các nguyện vọng em đăng ký.\nĐây là hướng dẫn đăng ký của trường ĐHCN anh/chị có thể tham khảo:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\n\n'),
(225, 'Cho m xin mã trường và danh sách mã ngành', 'Chào em, Đây là hướng dẫn viết đăng ký của trường để bạn tham khảo:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nNếu bạn cần tư vấn kỹ hơn có thể gọi theo số: 02437547810.'),
(226, ' có thể cho em xin một ít thông tin về cơ kĩ thuật ko ạ', 'Chào em, Em có thể tham khảo về ngành CƠ kỹ thuật tại đây:\nhttps://uet.vnu.edu.vn/sinh-vien-nganh-co-ky-thuat-sau-khi-tot-nghiep-lam-viec-tai-dau/\nHướng dẫn đăng ký:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\n\n'),
(227, 'Cho em hỏi tiêu chí thứ tự nguyện vọng của các ngành của năm nay và năm trước được không ạ', 'Chào em, Không có thứ tự nguyện vọng năm nay và năm trước em ạ. Việc xếp thứ tự nguyện vọng là do mong muốn của em. Em yêu thích ngành nào, trường nào hơn thì nên xếp nên trước. Vì khi xét tuyển nếu điểm của em đỗ vào nhiều trường thì trường nào em để trước thì sẽ trúng tuyển vào trường đó. Nếu em thích nhiều ngành trong 1 trường chẳng hạn. Em có thể xếp các ngành trong trường liên tục rồi mới viết sang đến trường khác.\nChúc em ôn và thi tốt.\n\n'),
(228, ' Mã trường của đại học công nghê-Đại học QG Hà Nội là gì', 'Chào em, Mã trường Đại học Công nghệ là QHI.\nBạn có thể tham khảo hướng dẫn tại đây:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/.'),
(229, 'có nganh cong nhe thuc pham ko', 'Chào em, Trường không có ngành đó bạn ạ.\nBạn có thể tham khảo các ngành của trường ĐHCN tại đây:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/'),
(230, ' khi nào thì xét đến tiêu chí phụ v ad', 'Chào em, Ngành CNTT tuyển sinh theo nhóm ngành CNTT, mã nhóm ngành là CN1. Em tham khảo hướng dẫn:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nNhà trường xét tuyển theo kết quả thi THPT quốc gia và không có tiêu chí phụ em nhé.\nThân mến.'),
(231, 'Em muốn hỏi về việc đăng kí nguyện vọng ạ, trong bài đăng trên website của trường k  có nên em muốn hỏi về các ngành đạo tạo CLC khi điền nguyện vọng có phải ghi đầy đủ chi tiết tên ngành k ạ, hay ghi như thế nào ạ\n\n', 'Chào em, Ngành nào em cũng phải ghi đầy đủ tên nhóm ngành, mã nhóm ngành em nhé.\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nVí dụ : Mã ngành/nhóm ngành: CN8. Tên ngành/nhóm ngành: Khoa học Máy tính (CLC theo TT23)\nChúc em ôn và thi tốt.\nThân mến.'),
(232, 'Cho em hỏi là em đạt giải 3 môn tin học trong Olympic của ĐHQG thì có nằm trong diện xét tuyển thẳng của nhà trường không ạ\n\n', 'Chào em, Em nằm trong diện được Nhà trường rất mong muốn em ạ.\nEm lưu ý là hồ sơ tuyển thẳng phải được chuyển về sở GDĐT trước ngày 20/5/2018.Mục 2.8 trong đề án hướng dẫn tuyển thẳng em nhé:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=1aeefrqq8a_5&_afrLoop=32002994726424657\nChào đón em đến với trường ĐH Công nghệ.\n\n'),
(233, 'Trường có khoa điện tử viễn thông không ạ..', 'Chào em, Trường ĐHCN có Khoa ĐTVT. Đây là 1 trong 2 khoa tiền thân của Nhà trường. Em có thể tham khảo tại đây: http://fet.uet.vnu.edu.vn/'),
(234, 'Em muốn hỏi ngành tự động hóa là CN6 : Kỹ thuật cơ điện tử ạ ? Với lại nếu e đăng kí nguyện vọng là CN6 thì chỉ có mỗi ngành đấy thôi nhỉ ? Kiểu e đăng kí CN1 thì có tận 4 ngành trong đấy , CN6 là chỉ 1 ngành hay bao gồm cả nhóm ngành kĩ thuật ạ ?  Thầy cô phân biệt cho e công nghệ thông tin vs kỹ thuật máy tính với , cả tự động hóa vs CNTT thì nên học cái nào nhỉ ?\n\n', 'Chào em, Ngành Công nghệ Kỹ thuật cơ điện tử có mã là CN6 chỉ có 1 ngành này thôi, nên khi em trúng tuyển\nvào CN6 thì trúng tuyển vào ngành này luôn. Kỹ thuật máy tính em có thể tham khảo tại đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/151\nCông nghệ kỹ thuật cơ điện tử em có thể tham khảo tại đây:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-co-dien-tu/\nNói chung cả 2 ngành em đề cập ở đây đều là các ngành có tính liên ngành kết hợp Điện tử viễn\nthông, Cơ, và CNTT. Đây chính là xu thế việc làm của nền cách mạng công nghiệp 4.0 hiện nay. Quan trọng là em cảm thấy yêu thích cái nào hơn thôi. Chị nghĩ ngành nào có hấp dẫn riêng. Chúc em ôn và thi thật tốt.\n\n'),
(235, 'cho em hỏi, khoa công nghệ thông tin (CN1) và khoa học máy tính (CN8) của trường đào tạo có gì khác nhau ạ?', 'Chào em, Chị gửi cho em thông tin về ngành KHMT(CLC):\nhttps://uet.vnu.edu.vn/nganh-khoa-hoc-may-tinh-chat-luong-cao/\nvà thông tin về ngành CNTT: https://uet.vnu.edu.vn/nganh-cong-nghe-thong-tin/\nĐể em có cái nhìn chi tiết về 2 chương trình này. Nếu có gì chưa hiểu có thể tương tác tiếp với bộ phận hỗ trợ em nhé.\n\n'),
(236, '  Em muốn đăng ký ngành khoa học máy tính nhưng không thấy mã ngành ạ. Em lên trang tuyển sinh của trường chỉ thấy mã ngành của khoa học máy tính (CLC) thôi ạ.\n\n', 'Hiện nay nhà trường chỉ còn chương trình KHMT CLC theo thông tư 23 em ạ. Mã ngành của ngành KHMT (CLC theo TT23) là CN8.'),
(237, 'E muốn đ.kí thi trường đại học công nghệ thuộc đại học quốc gia hà nội. E muốn biết thêm về trường cũng như mã trường mã ngành công nghệ thông tin mà e muốn đ.kks. E cảm ơn\n\n', 'Chào em, Chị gửi em hướng dẫn đăng ký:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/.\nThông tin về trường em có thể tham khảo trên website của trường:\nhttps://uet.vnu.edu.vn/category/tuyen-sinh/dai-hoc/\nNgoài ra em có thể tương tác với các anh chị khóa trên thông qua trang\nfb:https://www.facebook.com/TVTS.UET.VNU/'),
(238, 'cho e hỏi, e muốn thi vào trường thì ở hồ sơ của e, phần nguyện vọng ý, phần mã ngành, nhóm ngành e phải ghi như thế nào ạ\n\n', 'Chào bạn, Nhà trường gửi bạn hướng dẫn viết hồ sơ:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\nBạn cần thông tin chi tiết hơn có thể gọi điện theo số: 02437547810.\n\n'),
(239, 'Thông tin tuyển sinh 2018 của trường', 'Chào bạn,Nhà trường gửi bạn thông tin tuyển sinh của trường:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=1aeefrqq8a_5&_afrLoop=32002994726424657\nVà hướng dẫn viết đăng ký:\nhttps://uet.vnu.edu.vn/huong-dan-thi-sinh-dien-thong-tin-dang-ky-xet-tuyen-nam-2018-vao-truong-dai-hoc-cong-nghe/\n\n'),
(240, 'Mã gành của khoa công nghệ kỹ thuật điện tử truyền thông (CLC)', 'Chào bạn,Mã ngành của ngành Công nghệ kỹ thuật điện tử-viễn thông (CLC) là CN9. Bạn có thể tham khảo tại đây: https://uet.vnu.edu.vn/category/tuyen-sinh/dai-hoc/'),
(241, ' mã trường và mã ngành CNTT của trường là gì', 'Mã trường: QHI.\nMã nhóm ngành CNTT: CN1.\nBạn lưu ý là trường tuyển sinh theo nhóm ngành, sau khi trúng tuyển vào nhóm ngành sẽ xét ngành sau theo nguyện vọng, điểm và chỉ tiêu.'),
(242, 'Mã ngành công nghệ kỹ thuật cơ điện tử', 'Mã trường: QHI.\nMã nhóm ngành CNTT: CN1.\nBạn lưu ý là trường tuyển sinh theo nhóm ngành, sau khi trúng tuyển vào nhóm ngành sẽ xét ngành sau theo nguyện vọng, điểm và chỉ tiêu.'),
(243, 'có phải là: Mã trường:  QHI Mã nhóm ngành: Công nghệ thông tin: CN1', 'Chào bạn,Đúng rồi bạn ạ. Bạn lưu ý là trường tuyển sinh theo nhóm ngành, sau khi trúng tuyển vào nhóm ngành sẽ xét ngành sau theo nguyện vọng, điểm và chỉ tiêu.'),
(244, 'Em được giải ba quốc gia trong cuộc thi khoa học kỹ thuật cấp quốc gia,sản phẩm của em thuộc lĩnh vực phần mềm hệ thống.Em tìm hiểu và thấy trường có tuyển thẳng theo diện này.Vậy em phải đăng ký hồ sơ như thế nào?\n\n', 'Chào em, Em sẽ được tuyển thẳng vào trường, hồ sơ tuyển thẳng em làm theo hướng dẫn của bộ mục III, hồ sơ phải nộp về sở GĐĐT trước ngày 20/5/2018.\n\n'),
(245, 'ma truong la gi', 'Mã trường ĐH Công nghệ: QHI\nMã ngành bạn tham khảo tại đây:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=1aeefrqq8a_5&_afrLoop=32002994726424657\n(mục 2.4)'),
(246, ' năm nay trường có lấy khối thi A02 nữa không ạ?', 'Chào em, Năm nay trường không còn xét tổ hợp A02, các tổ hợp xét tuyển của  trường gồm: A00, A01, D07.'),
(247, 'Ban quản trị cho em hỏi năm nay trường mình chỉ tuyển sinh ngành khoa học máy tính theo chương trình chất lượng cao chứ ko tuyển sinh khoa học máy tính theo chương chỉnh chuẩn như năm 2017 nữa ạ.', 'Chào bạn ,Hiện nay Nhà trường chỉ còn ngành KHMT chất lượng cao.Thông tin chi tiết bạn có thể xem tại\nđây:https://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657'),
(248, 'em muốn biết thông tin tuyển sinh', 'Chào em, Chị gửi em đề án tuyển sinh của trường, mã ngành em có thể xem ở mục 2.6:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657'),
(249, 'Thầy cô có thể cho em xin mã ngành và nhóm ngành của trường mình năm nay tuyển sinh không ạ', 'Chào em,\nMã ngành của trường em có thể xem tại mục 2.6 của đề án tuyển sinh đã được công bố:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657\nThân mến.\n\n'),
(250, 'em đang phân vân giữa ngành CNTT và CNTT định hướng Nhật bản không biết hai ngành này khác nhau như thế nào ạ?', 'CNTT định hướng thị trường Nhật Bản cơ bản sẽ đào tạo các kiến thức nền tảng như của ngành CNTT, nhưng các em sẽ được học một số các môn học theo đặc thù các doanh nghiệp Nhật Bản, các kỹ năng mềm quan trọng để làm việc trong môi trường doanh nghiệp CNTT nói chung và Nhật Bản nói riêng.  Ngoài ra, sinh viên được học tiếng Nhật với giảng viên người Việt và người Nhật có kinh nghiệm, được thực tập tại các công ty công nghệ Nhật Bản trong quá trình học tập và nhiều cơ hội làm việc cho các công ty công nghệ tại Nhật Bản sau khi tốt nghiệp.\n\n'),
(251, 'em muốn đăng kí đăng kí hai ngành thì như nào ạ ?', 'Chào em,\nEm muốn đăng ký 2 ngành ở 2 nhóm ngành thì em cứ viết theo thứ tự ưu tiên ngành nào em thích hơn lên trước. Nếu 2 ngành trong cùng 1 nhóm ngành thì em chỉ cần đăng ký theo nhóm ngành (mã nhóm ngành và tên nhóm ngành là đủ). Việc xét ngành sẽ tiến hành sau khi em trúng tuyển vào nhóm ngành.\nThân mến.\n\n'),
(252, 'Cho em hỏi là trường mình công nhận bằng tiếng Anh gì để thay thế điểm tiếng Anh B1 ở trường ạ ?  và cụ thể điểm của bằng đó là bao nhiêu ạ ?\n\n', 'Chào em, các chứng chỉ quốc tế và chứng chỉ của ĐHQNN, ĐHQGHN có điểm tương đương B1 thì sẽ được miễn B1 em nhé.\nIELTS: 4.5\nTOEFL: 450   ITP, 133   CBT,      45 iBT\nTOEIC: 450\nCambridge Exam: PET\nBEC: Preliminary\nBULATS: 40\nCEFR: B1\nThân mến.\n\n'),
(253, 'dạ em muốn xin điểm sàn năm ngoái ạ', 'Chào em,\nChị gửi cho em thông tin điểm chuẩn các năm vào trường ĐHCN:\nhttps://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\nThân mến.\n\n'),
(254, 'em muốn xin mã nghành trường đại học công nghệ ạ', 'Chào em,\nMã ngành trường ĐHCN em xem tại mục 2.6 của đề án tuyển sinh:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657\nCó 9 mã nhóm ngành từ CN1 đến CN9 đấy em ạ. Lưu ý là mình đăng ký theo nhóm ngành em nhé.\nThân mến\n\n'),
(255, 'cho e hỏi sao k có mã ngành ạ? đkí theo mã nhóm ngành ạ?', 'Chào em,\nTrường tuyển sinh theo nhóm ngành. Nên em ghi mã nhóm ngành và tên nhóm ngành. Sau khi trúng tuyển vào nhóm ngành sẽ xét tiếp vào ngành theo nguyện vọng, điểm và chỉ tiêu của từng ngành.\nThân mến.\n\n'),
(256, 'Em chưa biết về mã ngành của trường mình năm 2018 ạ. Không biết em có thể xem mã ngành ở đâu vậy ạ. Em cảm ơn', 'Chào em,\nEm vào đây để xem mã ngành/nhóm ngành em nhé, mục 2.6:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657\nEm lưu ý là đăng ký theo nhóm ngành nên khi ghi mình ghi mã trường là QHI, mã ngành sẽ ghi mã nhóm ngành và tên nhóm ngành. Việc phân ngành trong nhóm ngành sẽ được tiến hành sau khi em trúng tuyển vào nhóm ngành.\nThân mến.\n\n'),
(257, 'E muốn học về lập trình ios thì nên đli khoa nào ạ?', 'Em nên thi khoa CNTT em ạ.\nNếu em cần thêm ý kiến của các anh chị đi trước có thể vào trang:\nhttps://www.facebook.com/TVTS.UET.VNU/'),
(258, 'có học bổng hay xét học bạ ko', 'Học phí của nhà trường đối với chương trình chuẩn tại mục 2.10: https://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657. Chương trình chất lượng cao theo thông tư 23 là 35 triệu/năm và ổn định trong cả 4\nnăm.Học bổng cho các em tại đây:\nhttps://uet.vnu.edu.vn/danh-sach-cac-hoc-bong-hang-nam-danh-cho-sinh-vien-dai-hoc-cong-nghe/\nKhông xét học bạ em ạ.'),
(259, 'ngành công nghệ thông tin của đại học công nghệ đại học quốc gia có xéttuyển NV2 ko  ạ?và nếu lấy NV2 thì có lấy ngang điểm với thí sinh đăng kí NV1 từ đầu ko ạ?', 'Chị chưa hiểu ý em NV2 ở đây là gì?\nVí dụ em đăng ký NV 1 là trường nào đó nhưng em không đủ điểm thì hệ thống sẽ tự xét\nem sang nguyện vọng 2 của em khi đó nguyện vọng 2 tính như nguyện vọng 1.\nNếu em nói NV2 là đợt bổ sung thì phải đợi kết quả xét tuyển của đợt 1. Nên chị không trả lời được câu hỏi của em.'),
(260, ' CHO e hỏi các mã ngành tuyển sinh trg mình năm nnay ạ', 'Chị gửi em danh sách các ngành, em kích vào từng ngành sẽ có mã ngành em nhé:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nGhi theo mã nhóm ngành và tên nhóm ngành em ạ.\nĐối với nhóm ngành có từ 2 ngành thì việc phân ngành sẽ quyết định sau khi em trúng tuyển vào nhóm ngành theo nguyện vọng, điểm và chỉ tiêu em ạ.'),
(261, 'Em chào thầy/cô! Em muốn tìm hiểu về đề án tuyển sinh của trường mình năm 2018', 'Đề án tuyển sinh của Trường ĐH Công nghệ:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=8v2r9n4v2_5&_afrLoop=31761799715318657\nCác ngành đào tạo của trường:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nNếu em cần tư vấn kỹ hơn có thể gọi điện theo số: 02437547810'),
(262, 'Em muốn đăng ký ngành công nghệ thông tin và em muốn hỏi một vài thông tin về ngành này.', 'Chị gửi e thông tin về ngành công nghệ thông tin: \nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/           Chị cũng trao đổi thêm rằng ngành CNTT hiện nay vẫn đang là 1 ngành khát nhân lực. Nhu cầu tuyển dụng đang rất lớn, quan trọng là sinh viên ra có làm được việc không. Học ở trường ĐHCN chị muốn em xác định rằng em học sẽ vất vả, không thể vừa học vừa chơi. Trường ĐHCN mong muốn sinh viê n của mình khi ra trường phải làm được việc và khẳng định thương hiệu của ĐHCN nên yêu cầu sinh viên phải có kiến thức thật, học thật và thi thật em nhé.\nChị gửi em tham khảo khung chương trình ngành CNTT:\nhttps://uet.vnu.edu.vn/nganh-cong-nghe-thong-tin/'),
(263, 'Nếu em chưa biết gì về lập trình thì có học được ngành này không ạ? Em đang học khối A1 nhưng tiếng anh của em cũng không được tốt lắm, vậy có học được công nghệ thông tin không ạ?', 'Khi em trúng tuyển thì nhà trường sẽ đào tạo căn bản từ đầu cho các em chưa biết gì.\nCũng tương tự, tiếng Anh là kỹ năng quan trọng, là công cụ để em đọc tài liệu, nghiên cứu, cũng như đáp ứng được yêu cầu của xã hội hội nhập ngày nay. Nên trong quá trình học em sẽ được trau dồi và tích lũy dần.\nChúc em học và thi tốt.\nThân mên.'),
(264, 'Em đăng kí ngành công nghệ thông tin và ngành công nghệ thông tin định hướng thị trường nhật bản mà chỉ thấy có mã của nhóm ngành thôi. Lm sao để biết mã nghành để đăng kí nguyện vọng ạ', '2 ngành mà em yêu thích nằm trong nhóm ngành CNTT. Việc phân ngành học (đối với các nhóm có 2\nngành trở lên) được thực hiện ngay sau khi thí sinh trúng tuyển vào trường trên cơ sở nguyện vọng\ncủa thí sinh, điểm thi và chỉ tiêu đào tạo ngành do Trường quy định.\nDo đó em chỉ cần đăng ký mã nhóm ngành là CN1 thôi.\nChúc em ôn và thi tốt.\nThân mến.'),
(265, 'Vậy nếu em ko đủ điểm đỗ CNTT mà điểm HTTT em cao hơn thì nhà trường vẫn sẽ xếp em vào HTTT ạ. Cho em hỏi thêm mà mã trường mình là gì v ạ ???', 'Việc phân ngành học (đối với các nhóm có 2 ngành trở lên) được thực hiện ngay sau\nkhi thí sinh trúng tuyển vào trường trên cơ sở nguyện vọng của thí sinh, điểm thi và chỉ tiêu đào\ntạo ngành do Trường quy định.\nNên trước hết em phải đủ điểm đỗ vào nhóm ngành đã. Sau đó dựa trên nguyện vọng và\nchỉ tiêu để xét tiếp.\nMã trường: QHI\nMã nhóm ngành: CN1'),
(266, 'con em năm nay thi đại học ! cháu học khối a đang loay hoay chon nghành học xin tư vấn giúp với a', 'Chào chị,\n\nCháu nhà mình yêu thích ngành gì và năng lực học cháu ra sao ạ?\nNhà trường gửi chị thông tin tuyển sinh của ĐHCN năm nay:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=db74agdjg_5&_afrLoop=31589244589290657\nNếu chị cần tư vấn kỹ hơn có thể gọi điến số 02437547810.\nTrân trọng.'),
(267, 'Trường có thể cũng cấp cho e biết tất cả mã ngành được không ạ ?', 'Nhà trường gửi bạn danh sách các ngành:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nBạn click vào các ngành bạn quan tâm sẽ có mã ngành chỉ tiêu và cách tính điểm bạn\nnhé.\nNếu bạn cần tư vấn kỹ hơn có thể gọi đến số 02437547810.\nThân mến.'),
(268, ' Ad ơi cho em hỏi chuyên ngành vật lí kĩ thuật đào tạo về những gì ạ', 'Ngành Vật lý Kỹ thuật đào tạo về Cơ sở vật lý hiện đại, vật lý ứng dụng, Khoa học và Công nghệ\nnano, Vật liệu và Linh kiện tiên tiến trong các lĩnh vực Vi điện tử, Năng lượng xanh, Y-sinh và Môi trường. Sinh viên được thực tập và NCKH tại phòng thí nghiệm trọng điểm và hệ thống các phòng thí nghiệm & thực hành với trang thiết bị hiện đại về công nghệ nano, nano quang tử, nano sinh học. Sinh viên tốt nghiệp có nhiều cơ hội làm việc tại các tập đoàn công nghệ tiến tiến như Samsung, Sumitomo Bakelite,… hoặc tiếp tục theo học sau đại học ở trong nước và nước ngoài.\nChị gửi em 1 công trình gần đây của nhóm sinh viên vật lý kỹ thuật:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/153\nThân mến.'),
(269, 'công nghệ thông tin và khoa học máy tính của trường công nghệ thông tin của đại học quốc gia hà nội', 'Đây là trang tư vấn của ĐHCN. Để đăng ký vào ngành CNTT em sẽ đăng ký theo nhóm ngành CNTT có mã nhóm ngành là CN1, các tổ hợp xét tuyển gồm: A00, A01, D07.\nChi tiết em xem tại đây: http://tuyensinh.vnu.edu.vn/index.php/Home/viewnganh/10\nNgành Khoa học máy tính CLC có mã CN8, tổ hợp xét tuyển A00, A01, D07 (trong đó toán anh hoặc toán lý nhân hệ số 2)\nCác ngành của đơn vị khác em xem trên trang: http://tuyensinh.vnu.edu.vn/\nThân mến.'),
(270, 'Em hiện đang là học sinh lớp 12. Em có dự định thi vào trường, thầy (cô) có thể cho em hỏi một vài điều được không ạ?', 'Em quan tâm đến ngành nào? Em muốn hỏi điều gì?\nNhà trường gửi cho em một số thông tin tuyển sinh của trường để em tham khảo nhé.\nCác ngành: http://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nGiới thiệu về ngành:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nEm cần thông tin chi tiết hơn có thể gọi: 02437547810\nThân'),
(271, ' Cho e hỏi khoa khoa học máy tính clc năm ngoái lấy 24 điểm tổ hợp khối a1  toán anh có nhân đôi không ạ?', 'Khoa học máy tính CLC năm ngoái xét tổ hợp A01, D07, D08 và toán anh nhân hệ số 2.\nNăm nay nhà trường xét tuyển theo các tổ hợp: A00, A01, D07 trong đó toán anh hoặc toán lý nhân hệ số 2.'),
(272, 'Tôi muốn đăng kí thi vào trường cả 2 ngành CNTT và Hệ thống TT  trong nhóm ngành CNTT thì ghi ở mục 21 trong Phiếu ĐKDT như thế nào? Cám ơn', '\nNgành CNTT và ngành HTTT trong cùng 1 nhóm ngành CNTT có mã là CN1, sau khi trúng\ntuyển vào nhóm ngành việc phân ngành được thực hiện ngay sau khi thí sinh trúng tuyển vào trường\ntrên cơ sở nguyện vọng của thí sinh, điểm thi và chỉ tiêu đào tạo ngành do Trường quy định.\nNên bạn chỉ cần ghi nhóm ngành CNTT mã nhóm ngành CN1.\nThân.'),
(273, 'cho em hỏi các ngành CLC thường lấy điểm thấp hơn bình thường ạ?', '\nSo sánh điểm của 2 chương trình mà cách xét điểm khác nhau thì cũng không thể chính\nxác được em ạ.\nĐối với chương trình chuẩn\n        ĐX = (Môn 1 + Môn 2 + Môn 3) + Điểm ƯT (ĐT,KV) (ĐX được làm tròn đến hai chữ số\nthập phân)\nĐối với chương trình CLC\n        ĐX = (Môn chính 1 x 2 + Môn chính 2 x 2 + Môn 3) x 3/5 + Điểm ƯT (KV, ĐT) (ĐX được\nlàm tròn đến hai chữ số thập phân)\nNên em cũng cân nhắc xem mình muốn học theo chương trình nào em nhé.\nThân.\n'),
(274, ' em muốn biết tiêu chí phụ của trường', '\nNhà trường xét tuyển theo kết quả thi THPT quốc gia em ạ. Không có tiêu chí phụ em\nnhé.\nChi tiết em xem tại đây:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=1dbib7bxjo_13&_afrLoop=31504458819369743\nThân mến.'),
(275, 'Năm nay trường mình xét tuyển những khối nào ạ', 'Năm nay mình xét tuyển theo 3 tổ hợp\n-        Toán, Lý, Hóa (Toán, Lý hệ số 2) (A00)\n-        Toán, Anh, Lý (Toán, Anh hệ số 2) (A01)\n-        Toán, Anh, Hóa (Toán, Anh hệ số 2) (D07)\n-        Hoặc chứng chỉ A-Level (đối với chương trình CLC)\nEm có thể tham khảo thông tin tại đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nThân mến.'),
(276, ' cho e hỏi nếu đỗ vào trường vs kq thị THPTQG thì có phải thi thêm kì thi nào nữa ko ạ', '\nEm muốn thi vào ngành nào của trường ĐHCN?\nNếu em đã đỗ vào trường, chẳng hạn ngành CNTT mà muốn học chương trình Chất lượng\ncao thì em sẽ phải trải qua 1 kỳ thi nữa. Riêng yêu cầu về ngoại ngữ các em sẽ được thi 1 kỳ thi\nđể sát hạch trình độ tiếng anh để phân lớp và có giải pháp bồi dưỡng phù hợp.\nThân mến.'),
(277, 'cho em hỏi mã ngành công nghệ thông tin trường mình là CN1 ạ để em điền vào hồ sơ', 'Công nghệ thông tin mã là CN1 em ạ, mã trường QHI:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnganh/10\nChúc em ôn thi tốt.\nThân mến.'),
(278, ' cách xét nguyện vọng năm nay là như thế nào ạ? nếu nguyện vọng trên đỗ thì những nguyện vọng dưới có được xét k ạ?', 'Cách xét tuyển năm nay cũng như năm ngoái. Trường em yêu thích nhiều hơn thì xếp lên\ntrên bởi khi điểm của em đủ để đỗ vào nhiều nguyện vọng khác nhau thì em sẽ trúng tuyển vào\nnguyện vọng đầu tiên em mà em đủ điểm.\nChúc em có những lựa chọn đúng đắn.\nThân mến.'),
(279, 'cho em hỏi thông tin tuyển sinh năm 2018', 'Đây là thông tin tuyển sinh của trường:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=h54ptf8vw_5&_afrLoop=31483552858764743\nNếu em cần tư vấn kỹ hơn thì có thể gọi điện theo số: 02437547810\nThân mến.');
INSERT INTO `list_ques` (`id`, `question`, `answer`) VALUES
(280, 'sao không có đào tạo kỹ sư ạ/?', 'Tỉ lệ có việc làm của sinh viên em có thể xem dựa trên phân tích của phòng Công tác sinh viên đối với 2 khóa ra trường gần nhất:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/77 và\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/160\nNhà trường có 7 ngành đào tạo kỹ sư, em có thể tham khảo các ngành tại đây:\nhttps://uet.vnu.edu.vn/thong-tin-de-tuyen-sinh-cua-truong-dai-hoc-cong-nghe-nam-2018/\nmục 2.4 emư nhé.\nThân mến.'),
(281, 'cho em hỏi vì sao ngành Khoa học máy tính bình thường và CLC năm nay lại gộp thành 1 ạ?nếu em muốn thi ngành này thì phải trả học phí cao hay như những ngành khác ạ?', 'Ngành Khoa học máy tính hiện nay không còn ở hệ chuẩn nữa mà chỉ có chương trình CLC thôi.\nChương trình CLC thì học phí là 35 triệu/năm và ổn định trong 4 năm.\nTuy nhiên chương trình CLC thì các em sẽ được học tập và trang bị các điều kiện, cơ sở vật chất tốt nhất.\nNếu em cần tư vấn kỹ hơn có thể gọi điện theo số 02437547810.\nThân.'),
(282, 'em đoạt giải ba trong kì thi Khoa học kĩ thuật cấp quốc gia trường mình có tuyển thẳng không ạ. e thuộc nghành công nghệ thông tin( lĩnh vục phần mềm hệ thống)', 'Thí sinh đoạt giải nhất, nhì, ba trong kỳ thi chọn học sinh giỏi quốc gia; thí\nsinh đoạt giải nhất, nhì, ba trong Cuộc thi khoa học, kỹ thuật cấp quốc gia, đã tốt nghiệp THPT,\nđược tuyển thẳng vào đại học theo ngành phù hợp với môn thi hoặc nội dung đề tài dự thi mà thí sinh\nđã đoạt giải.\nNhư vậy em sẽ được tuyển thẳng vào các nhóm các ngành tương ứng môn tin học mục 2.8\ntrong đề án:\nhttps://thituyensinh.vn/frontendTs/faces/TkTs2018?_adf.ctrl-state=h54ptf8vw_5&_afrLoop=31483552858764743\nThân mến.'),
(283, 'tôi muốn biết mã trường và mã ngàng', 'Chào chị,\n\nChị có thể tham khảo mã trường và mã ngành tại đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nNếu chị cần tư vấn kỹ hơn có thể gọi điện đến số: 02437547810.\nTrân trọng.'),
(284, 'Em muốn tìm hiểu về trường mình ạ', 'Em có thể xem trên website của trường: https://uet.vnu.edu.vn/\nNếu em cần thông tin cụ thể hơn thì có thể gọi điện đến số: 0243 7547810\nThân mến.'),
(285, 'các trường thpt chuyên không thuộc ĐHQGHN được xét tuyển thẳng như thế nào?', 'Học sinh THPT chuyên thuộc ĐHQGHN được xét tuyển thẳng và xét tuyển vào bậc đại học tại ĐHQGHN phải đỗ tốt nghiệp THPT, có hạnh kiểm 3 năm học THPT đạt loại Tốt và đáp ứng một trong các tiêu chí sau:\n+ Là thành viên chính thức đội tuyển dự kỳ thi Olympic hoặc các cuộc thi sáng tạo, triển lãm khoa học kỹ thuật khu vực, quốc tế;\n+ Đạt giải chính thức trong kỳ thi chọn học sinh giỏi bậc THPT cấp ĐHQGHN;\n+ Đạt giải chính thức trong kỳ thi Olympic chuyên Khoa học tự nhiên bậc THPT được tổ chức hàng năm;\n+ Là thành viên chính thức của đội tuyển tham dự kỳ thi chọn học sinh giỏi quốc gia hoặc các cuộc thi sáng tạo khoa học kỹ thuật quốc gia;\n+ Đạt danh hiệu học sinh giỏi từng năm học trong cả 3 năm THPT và có tổng điểm 4 bài thi/môn thi tốt nghiệp THPT đạt tối thiểu 28,0 điểm trong đó không có điểm bài thi/môn thi nào dưới 5,0 điểm;\nThân mến.'),
(286, 'Cho e hỏi tất cả những gì liên quan đến ngành hệ thống thông tin ạ!', 'Ngành hệ thống thông tin em có thể tham khảo tại đây:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nHTTT thực ra trong nhóm ngành CNTT, giữa các ngành không có sự phân biệt quá lớn, sau khi các em\nra trường xin việc nhà tuyển dụng cũng vẫn chỉ yêu cầu cơ bản của ngành CNTT. Nhu cầu nhân lực đối\nvới các nhóm ngành công nghệ và kỹ thuật hiện nay là rất lớn và rất thiếu, quan trọng là em chọn trường nào có uy tín và khẳng định đầu ra từ chính các thế hệ sinh viên đã ra trường.\nEm có thểm tham khảo phân tích việc làm SV Công nghệ 2 khóa gần đây:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnews/160\nThân.'),
(287, 'em muốn hướng sau này mình sẽ mở một cửa hàng để kinh doanh về thiết bị điện tử và máy tính, laptop. vậy em nên theo ngành nào sẽ vừa giúp ích cho mình trong việc kinh doanh buôn bán máy tính, laptop. em có nên theo ngành công nghệ thông tin không ạ', 'Chị nghĩ ngành Công nghệ thông tin là gần nhất với nguyện vọng của em.\nChị gửi em thông tin tuyển sinh của trường:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/listnganhuni/QHI\nThân'),
(288, 'Em chào các thầy cô. Em có thắc mắc mong các thầy cô giải đáp giúp em. Năm nay em có dự định đăng kí dự thi vào trường. Em muốn hỏi trong các tổ hợp điểm xét tuyển vào\ncác ngành trong trường có xét thêm điểm môn tiếng Anh không ạ? Mong các thầy cô giải đáp giúp em.', 'Các tổ hợp xét tuyển của trường ĐHCN gồm: A00, A01 và D07. Như vậy là có 2 tổ hợp có tiếng anh.\nNhà trường chỉ xét tuyển theo kết quả thi THPT quốc gia với 3 tổ hợp như vậy em nhé.\nEm cần chị tư vấn kỹ hơn thì có thể gọi điện cho chị theo số: 02437547810\nThân'),
(289, 'Các khối xét tuyển và phương thức xét tuyển', 'Nhà trường xét tuyển theo kết quả thi THPT quốc gia theo tổ hợp xét tuyển tương ứng;\nchứng chỉ quốc tế của Trung tâm Khảo thí ĐH Cambridge, Anh (Cambridge International\nExaminations A-Level, UK; sau đây gọi tắt là chứng chỉ A-Level));\nCác tổ hợp gồm: A00, A01, D07\nChi tiết bạn có thể xem tại đây:\nXét tuyển theo kết quả thi THPT quốc gia theo tổ hợp xét tuyển tương ứng; chứng chỉ\nquốc tế của\nTrung tâm Khảo thí ĐH Cambridge, Anh (Cambridge International Examinations A-Level,\nUK; sau đây gọi tắt là chứng chỉ A-Level));\nThân'),
(290, 'anh chị cho em hỏi về chỉ tiêu và các thông tin ngành hệ thống thông tin ạ.\n', 'Chào bạn,\n\nNhà trường gửi bạn thông tin chỉ tiêu tuyển sinh của ngành Hệ thông thông tin:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewnganh/64\nThân'),
(291, ' Em muốn hỏi về cơ chế tuyển thẳng đối với các thí sinh có giải quốc gia trong các cuộc  thi ạ', 'Chào em,\n\nNhà trường tuyển thẳng không giới hạn các bạn có giải quốc gia đối với các môn thi\ncó ngành tương\nứng tại trường Đại học Công nghệ. Nên nếu em yêu thích ngành nào thì cứ làm hồ sơ\nnộp như bình\nthường em nhé.\nChị gửi em thông tin tuyển thẳng trong Đề án tuyển sinh của trường:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/viewpage/24\nEm xem ở mục 2.8 em nhé.'),
(292, 'Chỉ tiêu tuyển sinh vào trường năm học mới này', 'Chỉ tiêu tuyển sinh của trường ĐHCN năm 2018:\nhttp://tuyensinh.vnu.edu.vn/index.php/Home/site/QHI\nBạn có thể kích vào từng ngành để xem chi tiết.\nThân'),
(293, 'e muốn học thạc sỹ CNTT', 'Đây là thông tin tuyển sinh sau đại học của trường:\nhttps://uet.vnu.edu.vn/category/tuyen-sinh/sau-dai-hoc/\nBạn cần gì có thể gọi trực tiếp đến số: 02437547810.\nThân'),
(294, 'cho em hỏi thông tin tuyển sinh cua trường', 'Chị gửi thông tin tuyển sinh của trường Đại học Công nghệ:\nhttps://uet.vnu.edu.vn/thong-tin-de-tuyen-sinh-cua-truong-dai-hoc-cong-nghe-nam-2018/\nEm cần gì thì có thể trao đổi tiếp.\nThân'),
(295, 'năm nay trường mình có tổ chức thi tuyển sinh kì thi riêng như năm ngoái ko ạ?', 'Bắt đầu từ năm 2017 nhà trường xét tuyển theo kết quả của kỳ thi THPT quốc gia rồi\nem nhé.\nNăm nay cũng vậy, Xét tuyển theo kết quả thi THPT quốc gia theo tổ hợp xét tuyển tương ứng; chứng chỉ quốc tế của Trung tâm Khảo thí ĐH Cambridge, Anh (Cambridge International Examinations A-Level, UK; sau đây gọi tắt là chứng chỉ A-Level));\nThân.'),
(296, 'Admin có thể cho mình biết  điểm chuẩn vào tất cả các ngành năm 2018 không ạ, nếu chưa có thì bao giờ mới có ạ?', 'Trước 17h00 ngày 06/8/2018 Nhà trường sẽ công bố điểm trúng tuyển vào trường theo\nđúng quy định.\nVậy nên em hãy ôn tập cho thật tốt và có kết quả thi tốt nhất. Việc còn lại là ngồi\nchờ đến ngày 06/8 em nhé.\nThân.'),
(297, 'cho e hỏi 1, các ngành thi năm ngoái năm nay vẫn như thế ạ và có thêm những ngành nào ạ 2, tổ hợp môn thi của các ngành công bố trước hay sau khi thi ạ? 3, đăng kí là đăng kí theo ngành hay theo nhóm ngành?', 'Nhà trường gửi em thông tin tuyển sinh năm nay của trường Đại học Công nghệ:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/\nNăm nay trường có  thêm 2 ngành mới là: Công nghệ Hàng không vũ trụ và Kỹ thuật\nrobot.\nTổ hợp các môn thi đã công bố luôn trong bảng thông tin tuyển sinh đấy em.\nNăm nay nhà trường vẫn cho đăng ký theo nhóm ngành.\nThân.'),
(298, 'Em muốn hỏi: các trường đại học có ngành công nghệ thông tin thì có giống nhau hay không , đăng ký vào trường nào cũng được miễn là đủ điểm là được hay sao. Em đang băn khoăn với ngành công nghệ thông tin của đại học bách khoa, với đại học công nghệ ĐHQG.Tư vấn cho em với, em xin cảm ơn ạ.', 'Chào em,\n\nMỗi ngành được mở ra đều phải có sự phê duyệt của Bộ và có những tiêu chí chung buộc phải có theo quy định. Tuy nhiên mỗi trường lại có thế mạnh riêng. Em hỏi trường ĐH Bách khoa thì liên hệ trực tiếp với trường BK để được tư vấn kỹ hơn và chuẩn hơn. Còn tại Trường Đại học Công nghệ: Ngành Công nghệ Thông tin đào tạo kiến thức và kỹ năng quan trọng và hiện đại về CNTT với mục tiêu đạt trình độ chung của khu vực và quốc tế, cho phép sinh viên tốt nghiệp ra trường có thể nhanh chóng đáp ứng các nhu cầu về hoạt động công nghệ thông tin của xã hội cũng như tiếp tục học tập, nghiên cứu và phát triển ngành Công nghệ Thông tin. Sinh viên tốt nghiệp ngành CNTT có thể làm tại các công ty công nghệ với nhiều vị trí khác nhau từ lập trình viên, lập trình các hệ thống thông minh, phân tích thiết kế hệ thống, kiểm thử phần mềm, quản trị mạng…\nTại trường ĐHCN nếu em theo học chương trình chất lượng cao thì em sẽ được nhà trường hỗ trợ tối\nđa. Trong quá trình học tập, nếu có môn nào chưa đạt yêu cầu đều được nhà trường gia sư hỗ trợ đến\nlúc phải đạt được yêu cầu môn học. Mục tiêu để những bạn khi vào trường chưa phải là giỏi chưa\nbiết gì về CNTT nhưng đến lúc bạn ra trường bạn phải là một người mà có thể làm được việc kể cả trong môi trường quốc tế.\nThân.'),
(299, 'Tư vấn đại học liên kết quốc tế', 'Chào bạn,\n\nNhà trường hiện không có chương trình liên kết quốc tế bạn nhé.'),
(300, 'e muốn biết trường mình có những ngành gì chuyên', 'Nhà trường gửi thông tin tuyển sinh của trường:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/\nVà mô tả chi tiết cho từng ngành:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nNếu bạn cần thêm thông tin nhà trường sẽ cung cấp.\nThân,'),
(301, 'Chào ạ! Xin phép cho em hỏi năm nay trường tuyển sinh theo những phương án nào và diễn ra vào thời gian nào. Tổ hợp môn xét tuyểnTHPTQG có những khối nào? Em xin trân thành cảm ơn!', 'Chị gửi em thông tin tuyển sinh của trường ĐHCN:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/\nTrường tuyển sinh theo kết quả thi THPT quốc gia, riêng chương trình chất lượng cao\ncó xét thêm\nbằng chứng chỉ A-level.\nTổ hợp môn kèm theo trong thông tin chỉ tiêu trong bảng em nhé.'),
(302, 'Hiện tại tình trạng sinh viên học xong có việc làm k ạ', 'Trên website trường có thống kê sinh viên ra trường của 2 năm gần\nđây:https://uet.vnu.edu.vn/trien-vong-nghe-nghiep-cua-sinh-vien-truong-dai-hoc-cong-nghe-dai-hoc-quoc-gia-ha-noi/\nem tham khảo nhé.\nThân'),
(303, 'trường có xét tuyển học bạ không ạ ? thi thì điểm số trung bình bao nhiêu thì đỗ ạ', 'Trường xét tuyển theo kết quả kỳ thi THPT quốc gia. Ngoài ra, chương trình chất lượng cao còn xét\nthêm chứng chỉ A level.\nĐiểm em có thể tham khảo điểm chuẩn các năm trước:\nhttps://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\nThân'),
(304, 'Em co nguyện vọng thi vào nganh tu dong hoa nhung khong biet  chi tieu nam nay cua truong nhu the nao. Ad tu van cho e duoc k a', '\nNhà trường có Khoa Cơ học kỹ thuật và tự động hóa.\nCác ngành của trường ĐHCN em có thể tham khảo tại đây:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/ và\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/.\nĐiểm chuẩn em xem tại đây:\nhttps://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\nThân'),
(305, 'Gửi thầy cô ban tư vấn tuyển sinh, Em đang sinh viên trường ĐHCN, ngành gần với ngành đào tạo cao học kỹ thuật phần mềm. Theo như thông tin khung đào tạo và tuyển sinh thì em cần học bổ sung các học phần: toán rời rạc, lập trình nâng cao, cơ sở dữ liệu, cấu trúc dữ liệu và giải thuật. Tuy nhiên hiện trong chương trình đào tạo bậc đại học, em đã học và có điểm 2 môn * Lập trình nâng cao *và *Cấu trúc dữ liệu và giải thuật* trong bảng điểm. Vậy em hỏi là nếu em có nguyện vọng học chương trình thạc sĩ kỹ thuật phần mềm thì em có cần phải học bổ sung/ thi bổ sung cho 2 môn này không? Em xin chân thành cám ơn!', 'Em cứ đăng ký trên cổng thông tin tuyển sinh. Khi nhà trường có bảng điểm của em thì sẽ căn cứ vào\nđó để quyết định em phải học bao nhiêu môn trong 4 môn yêu cầu. Nếu em là sv của trường mình thì\nkhả năng cao là không phải học em nhé.\nThân,'),
(306, 'trường đã có thông tin tuyển sinh đh năm 2018 chưa ạ', 'Bạn có thể xem thông tin tuyển sinh năm 2018 trường ĐHCN tại đây:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/\nThân'),
(307, 'Em có nguyện vọng thi vào ngành tự động hóa nhưng ko biết chỉ tiêu năm nay của trường như thế nào. Ad tư vấn cho em đc ko ạ? \n', 'Chị gửi lại em thông tin chỉ tiêu tuyển sinh của trường ĐH Công nghệ.\n(https://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/)\nThân.'),
(308, 'Em khong biết rằng ở đó học có khó lắm k', 'Theo năng lực đầu vào mà các em đã đỗ vào trường ĐH Công nghệ thì các em đều có thể học tốt chương trình học tập của mình. Tuy nhiên, em phải xác định trường ĐH Công nghệ là môi trường học thật và thi thật, để đảm bảo các em ra trường là những người nắm vững kiến thức và làm được việc, nên trong quá trình học tập em phải luôn cố gắng.\nThân'),
(309, ' e muốn thi  vào trường đại học công nghệ và chưa biết chọn ngành nào. E muốn biết thêm về nội dung học ạ?', 'Chị gửi cho em thông tin giới thiệu về các ngành của trường ĐHCN, em tham khảo và\nquyết định xem mình phù hợp với ngành nào, yêu thích ngành nào và khả năng học tập có thể vào ngành\nnào. Sau đó nếu cần tư vấn cụ thể hơn, em có thể liên lạc lại.\nCác ngành đào\ntạo:https://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nĐiểm trúng tuyển qua các\nnăm:https://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\nThân.'),
(310, 'Ad cho em hỏi  ngành kĩ thuật xây dựng giao thông của trường đào tạo về bên gì ạ??', 'Ngành Công nghệ kỹ thuật trong xây dựng–giao thông nay là ngành Công nghệ kỹ thuật\nxây dựng.\nNgành Công nghệ thuật xây dựng đào tạo kiến thức và kỹ năng chuyên sâu về thiết kế\nvà xây dựng công trình giao thông, công trình xây dựng dân dụng, quy hoạch đô thị. Sinh viên\nđồng thời được trang bị kiến thức về kết cấu công trình và vật liệu xây dựng tiên tiến. Sinh viên\nđược thực hành tại các phòng thí nghiệm hiện đại về cơ học và vật liệu tiên tiến đồng thời thực tập\ntại các tập đoàn xây dựng liên kết với Nhà trường. Kỹ sư tốt nghiệp có khả năng làm việc tại các\ncông ty thiết kế xây dựng, các tập đoàn xây dựng và các viện nghiên cứu chuyên ngành.'),
(311, 'Ngành khoa học máy tính có mức điểm đầu vào hàng năm khoảng bao nhiêu điểm ag?', '\nChị gửi em thông tin điểm chuẩn hàng năm của Nhà trường:\nhttps://uet.vnu.edu.vn/diem-trung-tuyen-vao-truong-dai-hoc-cong-nghe-qua-cac-nam/\nThân,'),
(312, ' khoa công nghệ hàng không vũ trụ đào tạo những công việc như thế nào ạ ?', 'Ngành Công nghệ Hàng không Vũ trụ đào tạo các kỹ sư đam mê chinh phục không gian. Chương trình đào tạo cung cấp các định hướng nghề nghiệp liên quan đến thiết kế, sản xuất các thiết bị bay, các hệ thống điều khiển, công nghệ vệ tinh, tên lửa. Đây là chương trình có nhiều ưu đãi cho sinh viên trong quá trình học tập và tốt nghiệp. Khoảng 30% sinh viên của chương trình sẽ được Viettel cấphọc bổng toàn phần (được miễn học phí và nhận học bổng phục vụ việc học tập) trong quá trình đàotạo; được thực tập, thực hành tại các phòng thí nghiệm hiện đại của Trường, Viện Hàng không Vũ trụ Viettel và Trung tâm Vũ trụ Việt Nam. Kỹ sư tốt nghiệp chương trình có nhiều cơ hội việc làm tại các Hãng hàng không, các Viện nghiên cứu trong và ngoài nước, ngoài ra, Viettel sẽ tuyển dụng trực tiếp các sinh viên tốt nghiệp loại giỏi, xuất sắc.\nEm cần tư vấn cứ trao đổi em nhé.'),
(313, 'em chào ad ạ....Năm nay em thi ĐH và e muốn thi vào CNTT của trường ĐHQGHN a...e có chút chưa hiểu là khi e thi vào CNTT của trường đó ạ thì e sẽ học về mảng nào vậy ạ..tại vì e ko thấy trường thông báo các mảng học như kĩ thuật phần mềm hay an toàn thông tin đó ạ...mong ad giải đáp giúp e với ạ... e cám ơn ạ', 'Học mảng nào là do em yêu thích đặc biệt ngành nào thì chọn ngành đó. Em xem giới thiệu từng ngành ở đây:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nNếu em học CNTT thì: đào tạo kiến thức và kỹ năng quan trọng và hiện đại về CNTT với mục tiêu đạt trình độ chung của khu vực và quốc tế, cho phép sinh viên tốt nghiệp ra trường có thể nhanh chóng đáp ứng các nhu cầu về hoạt động công nghệ thông tin của xã hội cũng như tiếp tục học tập, nghiên cứu và phát triển ngành Công nghệ Thông tin. Sinh viên tốt nghiệp ngành CNTT có thể làm tại các công ty công nghệ với nhiều vị trí khác nhau từ lập trình viên, lập trình các hệ thống thông minh, phân tích thiết kế hệ thống, kiểm thử phần mềm, quản trị mạng…(khi em học ngành CNTT thì trong khung chương trình sẽ có các môn học định hướng CN phần mềm, hoặc truyền dữ liệu và mạng máy tính,hệ thống thông tin..) do em lựa chọn em nhé.\nThân'),
(314, ' Em muốn hỏi trường năm nay dùng kết quả của kì thi thpt qg để xét tuyển hay phải thi đánh giá năng lực ạ.Em xin cảm ơn nhà trường', 'Nhà trường dùng kết quả của kỳ thi THPT quốc gia em nhé.\nChúc em ôn và thi tốt.'),
(315, '  Tôi quan tâm đến ngành (thí điểm) Công nghệ vũ trụ, tương lai ngành này thế nào ? cơ hội làm việc tại những đơn vị nào ?\n', '\nNgành Công nghệ Hàng không Vũ Trụ được mô tả chi tiết theo link:\nhttps://uet.vnu.edu.vn/viet-nam-co-vien-cong-nghe-hang-khong-vu-tru-sae/.\nHiện nay trong cả nước chỉ có 5 cơ sở có thể đào tạo về ngành này. Sau 4,5 năm học, sinh viên sẽ nhận bằng kỹ sư công nghệ hàng không vũ trụ và có cơ hội được làm việc, tham gia các dự án về hàng không vũ trụ tại Tập đoàn Viettel, Trung tâm Vũ trụ Việt Nam và các đơn vị khác (như Trung tâm vệ tinh quốc gia,...). Theo Thiếu tướng Nguyễn Mạnh Hùng, Tổng giám đốc Tập đoàn Viettel: “Chúng tôi không cam kết tiếp nhận các bạn về Viettel tham gia hành trình này. Bởi bất kỳ ai vượt qua 4 năm học tập căng thẳng, hoàn thành những dự án mà chưa một người Việt Nam nào làm được, với ý chí và tinh thần của những chiến binh thì Viettel sẽ phải bằng mọi cách mời các bạn về đội ngũ của mình”.\nNên bạn có thể yên tâm lựa chọn ngành này.\nThân mến.'),
(316, 'Em đang học bách khoa đà nẵng (điện tử viễn thông) . Cho e hỏi e có thể chuyển trg tới đại học công nghệ đại học quốc gia hà nội được k ạ. E năm nhất. Điểm thi thpt quốc\ngia năm trk 24.75', 'Một trong các Điều kiện để chuyển trường là bạn không là sinh viên năm đầu và năm cuối. Điểm đầu vào phải lớn hơn hoặc bằng điểm đầu vào của năm tuyển sinh tương ứng, như vậy nếu bạn muốn học chương trình chuẩn ngành Công nghệ kỹ thuật điện tử – viễn thông thì điểm của bạn không đáp ứng yêu cầu 26 điểm. Nếu bạn muốn học chương trình chất lượng cao ngành Công nghệ kỹ thuật điện tử – viễn thông thì tổ hợp môn xét tuyển là: Toán lý anh, toán sinh anh, toán hóa anh trong đó toán anh nhân hệ số 2, nếu bạn tính tổ hợp môn mà có điểm trên 23.5 mới được xem xét.\nThân mến.\n           '),
(317, 'Tư vấn cho chi tiết cho em phương hướng xét tuyển và thông tin về công nghệ kĩ thuật ạ', 'Trường ĐH Công nghệ Xét tuyển theo kết quả thi THPT quốc gia theo tổ hợp các môn\ntương ứng; chứng chỉ quốc tế của Trung tâm Khảo thí ĐH Cambridge, Anh (Cambridge International\nExaminations A-Level, UK; sau đây gọi tắt là chứng chỉ A-Level));\nTổ hợp môn bạn có thể xem lại link:\nhttps://uet.vnu.edu.vn/chi-tieu-tuyen-sinh-truong-dai-hoc-cong-nghe-nam-2018/.\nThông tin về các ngành bạn có thể xem tại link:\nhttps://uet.vnu.edu.vn/gioi-thieu-cac-nganh-dao-tao-dai-hoc-cua-truong-dai-hoc-cong-nghe/\nNếu bạn cần tư vấn kỹ hơn có thể gọi theo số hotline trên website hoặc gửi câu hỏi\ntại đây. Nhà trường sẽ tư vấn tiếp cho bạn.'),
(318, 'Học sinh khối A1 có được đăng ký ngành công nghệ thông tin không?\n', 'Nếu em nhà mình có nguyện vọng học CNTT trường ĐH Công nghệ thì như cháu vừa tư vấn, nhà\ntrường xét tuyển dựa trên nhiều tổ hợp môn, em nhà mình học khối A1 là 1 lợi thế, ngoài chương trình đào tạo chuẩn bên trường cháu còn có chương trình đào tạo chất lượng cao đáp ứng thông tư 23 củaBộ GD&ĐT là chương trình rất chú trọng kỹ năng ngoại ngữ đáp ứng yêu cầu môi trường làm việc quốc tế. Nếu chú cần tư vấn thêm có thể liên hệ trực tiếp với Trường theo số: 0243 7547865.\nKính thư,\n'),
(319, 'Trường ĐH CN có tổ chức kỳ thi riêng không?, nếu có thì bao giờ thi?', 'Trường ĐH CN không tổ chức kỳ thi riêng mà xét tuyển dựa trên kết quả thi THPT quốc gia hoặc bài thi ĐGNL còn hạn sử dụng do ĐHQGHN tổ chức hoặc chứng chỉ quốc tế của Trung tâm Khảo thí ĐH Cambridge, Anh (A-Level).\nThân'),
(320, 'Hi Ban Tuyển sinh, mình có nhu cầu biết thông tin tuyển sinh thạc sĩ chuyên ngành kĩ thuật phần mềm\nnăm 2018. Bạn cho mình thông tin chi tiết với mình cám ơn nhiều. Các thông tin mình quan tâm như sau:\n - Khoá học\n         - Thời gian học    - Bằng cấp\n - Học phí', 'Nhà trường gửi bạn một số thông tin:\nHọc phí Cao học năm học 2017-2018:\n1.305.000đ/ tháng\n408.000đ/tín chỉ\nHọc ngoài giờ nhân hệ số 1.5\nHọc trả nợ = học lần đầu: hệ số 1\nHọc cải thiện = học lựa chọn tự do: hệ số 1.5\nTrừ lúc nhập học thu thêm Thẻ học viên, hồ sơ và tài liệu cho học viên:        145.000đ\nngoài ra khôngthu thêm bất cứ khoản nào khác.Phí đăng ký dự thi:\nLệ phí: 420.000đ/thí sinh/3 môn.\nPhương thức nộp tiền: thí sinh có thể chuyển lệ phí tuyển sinh theo quy định vào tài\nkhoản của\nTrường Đại học Công nghệ hoặc nộp trực tiếp bằng tiền mặt tại Trường Đại học Công\nnghệ.\nPhí ôn thi:\nÔn Tin học cơ sở: full 15 buổi ( trong đó: 4 buổi Toán học rời rạc, 4 buổi cấu trúc  dữ liệu và giải thuật, 4 buổi Lập trình nâng cao, 3 buổi cơ sở dữ liệu). 1 buổi học 3 tiếng thu 150.000đ/buổi.\nÔn Kỹ thuật điện tử số: 3 buổi. 1 buổi 150.000đ/buổi.\nÔn Đánh giá năng lực: 1 buổi. 1 buổi 150.000đ/buổi.\nLịch cụ thể theo file đính kèm.\nThân.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `list_ques`
--
ALTER TABLE `list_ques`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `list_ques`
--
ALTER TABLE `list_ques`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=321;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
